name: BuildEXE
run-name: BuildEXE
on: [push]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          pyinstaller_ver: '==5.13.2'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'GDBot'
          options: --onefile, --name "GDBot", --windowed, 
